# Generated by Django 3.1.5 on 2021-03-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210318_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='busy', max_length=250, null=True, verbose_name='About you'),
        ),
    ]
