# Generated by Django 3.1.5 on 2021-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210318_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(max_length=50, null=True, verbose_name='nationality'),
        ),
    ]
