# Generated by Django 3.1.5 on 2021-02-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='description',
            field=models.CharField(blank=True, default="I'm glad you're visiting our shop!", max_length=350, null=True, verbose_name='shop description'),
        ),
    ]
