# Generated by Django 3.1.5 on 2021-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20210318_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='youtube'),
        ),
    ]
