# Generated by Django 3.1.5 on 2021-03-18 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0007_auto_20210318_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='coutomers'),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='customers_favorite',
            field=models.ManyToManyField(blank=True, related_name='customers_favorite', to=settings.AUTH_USER_MODEL, verbose_name='customers favorite'),
        ),
    ]
