# Generated by Django 3.1.5 on 2021-03-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('shops', '0008_auto_20210318_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.shopcategory', verbose_name='shop category'),
        ),
    ]
