# Generated by Django 3.1.5 on 2021-03-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20210318_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
    ]
