# Generated by Django 3.1.5 on 2021-02-22 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoprequests', '0002_auto_20210219_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprequest',
            name='request_approve',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Cancel', 'Cancel')], max_length=50, null=True, verbose_name='request_approval'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='requested_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
