# Generated by Django 3.1.5 on 2021-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoprequests', '0003_auto_20210222_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoprequest',
            name='user_address',
        ),
        migrations.AddField(
            model_name='shoprequest',
            name='street_address',
            field=models.CharField(max_length=50, null=True, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=50, verbose_name='gender'),
        ),
    ]
