# Generated by Django 3.1.5 on 2021-03-18 17:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shoprequests', '0005_auto_20210318_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprequest',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
