# Generated by Django 3.1.5 on 2021-03-18 17:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shoprequests', '0006_shoprequest_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprequest',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
