# Generated by Django 3.1.5 on 2021-03-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoprequests', '0007_auto_20210318_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprequest',
            name='address_proof',
            field=models.CharField(choices=[('1', 'Licence'), ('2', 'Government id')], max_length=50, null=True, verbose_name='address_proof'),
        ),
        migrations.AddField(
            model_name='shoprequest',
            name='address_proof_img',
            field=models.ImageField(null=True, upload_to='address_proof_img', verbose_name='Address Verification'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='id_proof_img',
            field=models.ImageField(null=True, upload_to='id_proof_img', verbose_name='ID Verification'),
        ),
    ]
