# Generated by Django 3.1.5 on 2021-03-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('shoprequests', '0009_auto_20210318_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprequest',
            name='shop_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.shopcategory', verbose_name='shop category'),
        ),
    ]
