# Generated by Django 3.1.5 on 2021-03-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoprequests', '0012_auto_20210322_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprequest',
            name='address_proof',
            field=models.CharField(choices=[('1', 'Licence'), ('2', 'Government id'), ('3', 'Passport')], max_length=50, verbose_name='address proof'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='id_proof',
            field=models.CharField(choices=[('1', 'Licence'), ('2', 'Government id'), ('3', 'Passport')], max_length=50, verbose_name='face verification'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='shop_address',
            field=models.CharField(max_length=75, verbose_name='shop address'),
        ),
        migrations.AlterField(
            model_name='shoprequest',
            name='shop_title',
            field=models.CharField(max_length=75, verbose_name='Shop title'),
        ),
    ]
